#!/bin/sh
# preinst script for wasta-remastersys
#
# see: dh_installdeb(1)

set -e

if [ -f /etc/wasta-remastersys/wasta-remastersys.conf ]
then
    mv /etc/wasta-remastersys/wasta-remastersys.conf \
       /etc/wasta-remastersys/wasta-remastersys.conf.old
fi

exit 0
